# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='from_date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='to_date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
