# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='subtotal',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
